### ISSUE TITLE
Build broken when using kotlin 1.7.21

### ISSUE THREAD

**Issue by doniwinata0309** [junit-team/junit5-samples#178]
Hi, when using kotlin 1.7.21, junit5 return error:
java.io.File org.jetbrains.kotlin.gradle.tasks.KotlinCompile.getDestinationDir()

This is the complete stacktrace:

```
Caused by: java.lang.NoSuchMethodError: 'java.io.File org.jetbrains.kotlin.gradle.tasks.KotlinCompile.getDestinationDir()'
at de.mannodermaus.gradle.plugins.junit5.providers.KotlinDirectoryProvider.classFoldersOf(Kotlin.kt:42)
at de.mannodermaus.gradle.plugins.junit5.providers.KotlinDirectoryProvider.mainClassDirectories(Kotlin.kt:28)
at de.mannodermaus.gradle.plugins.junit5.providers.BaseKt.mainClassDirectories(Base.kt:50)
at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport$ConfigAction.execute(AndroidJUnit5JacocoReport.kt:86)
at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport$Companion$create$1.execute(AndroidJUnit5JacocoReport.kt:36)
at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport$Companion$create$1.execute(AndroidJUnit5JacocoReport.kt:28)
at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:362)
at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport$Companion.create(AndroidJUnit5JacocoReport.kt:35)
at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin$configureJacocoTasks$1.execute(Plugin.kt:141)
at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin$configureJacocoTasks$1.execute(Plugin.kt:19)
at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:123)
at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:110)
at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)```

Do you have idea how to fix this issue? Thank you in advance

**Comment by sbrannen** [comment]
It looks like `AndroidJUnitPlatformPlugin` is not compatible with the version of Gradle in use.

**Comment by doniwinata0309** [comment]
I am using latest gradle  version 7.5.1. It working fine if using kotlin 1.6.20. Only broken when updating to kotlin 1.7.20

**Comment by marcphilipp** [comment]
Unless I'm missing sth. this looks like an issue with https://github.com/mannodermaus/android-junit5. Could you please raise an issue there?

**Comment by doniwinata0309** [comment]
sure i will raise there, thank you
