### ISSUE TITLE
Cannot create Launcher without at least one TestEngine

### ISSUE THREAD

**Issue by Vazzilena** [junit-team/junit5-samples#21]
Hey,

I am running the following in gradle: 

```groovy
junitPlatform {
    filters {
        engines {
            include 'junit-platform', 'junit-vintage', 'junit-jupiter'
       }
        tags {
            include 'categories.TestClassifier.ReliableIntegrationTest'
        }
    }
}
```

I believe I have configured the dependencies correctly:

```groovy
dependencies {
		classpath (
			"org.junit.platform:junit-platform-gradle-plugin:1.0.0-M3",
		)						
	}

apply plugin: "org.junit.platform.gradle.plugin"

configurations {
externalLibraries	
compile.extendsFrom (externalLibraries)
}

externalLibraries (group: 'org.junit.platform', name: 'junit-platform-commons', version: '1.0.0-M3')
externalLibraries (group: 'org.junit.platform', name: 'junit-platform-console', version: '1.0.0-M3')
externalLibraries (group: 'org.junit.platform', name: 'junit-platform-launcher', version: '1.0.0-M3')
externalLibraries (group: 'org.junit.platform', name: 'junit-platform-runner', version: '1.0.0-M3')
externalLibraries (group: 'org.junit.platform', name: 'junit-platform-gradle-plugin', version: '1.0.0-M3')
externalLibraries (group: 'org.junit.platform', name: 'junit-platform-engine', version: '1.0.0-M3')
externalLibraries (group: 'org.junit.vintage', name: 'junit-vintage-engine', version: '4.12.0-M3')	
externalLibraries (group: 'junit', name: 'junit', version: '4.12')
externalLibraries (group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.0.0-M3')
externalLibraries (group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.0.0-M3')
```

No matter how I adjust the engines (specify just one engine, list all or comment out the engine part entirely)  I always run in this error:

```
Feb 22, 2017 3:21:14 PM org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry loadTestEngines
INFO: No TestEngine implementation discovered.
org.junit.platform.commons.util.PreconditionViolationException: Cannot create Launcher without at least one TestEngine; consider adding an engine implementation JAR to the classpath
        at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:207)
        at org.junit.platform.launcher.core.DefaultLauncher.<init>(DefaultLauncher.java:52)
        at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:53)
        at org.junit.platform.console.tasks.ExecuteTestsTask.executeTests(ExecuteTestsTask.java:61)
        at org.junit.platform.console.tasks.ExecuteTestsTask.lambda$execute$0(ExecuteTestsTask.java:57)
        at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:33)
        at org.junit.platform.console.tasks.ExecuteTestsTask.execute(ExecuteTestsTask.java:57)
        at org.junit.platform.console.tasks.ConsoleTaskExecutor.executeTask(ConsoleTaskExecutor.java:38)
        at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:54)
        at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:39)
```

**Comment by sormuras** [comment]
Closing this issue as "out-of-date" and "not-using-Gradle-as-intended". Please consult the new minimal Gradle setup sample at https://github.com/junit-team/junit5-samples/blob/master/junit5-vanilla-gradle/build.gradle showing how you add a test engine to the runtime class-path.

If this issue still persists feel free to re-open it.
