### ISSUE TITLE
test failure

### ISSUE THREAD

**Issue by lx-931203** [junit-team/junit5-samples#89]
```
$ mvn test
$ mvn test
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------< com.example:junit5-jupiter-starter-maven >--------------
[INFO] Building junit5-jupiter-starter-maven 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ junit5-jupiter-starter-maven ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/alex/Desktop/junit5-samples/junit5-jupiter-starter-maven/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ junit5-jupiter-starter-maven ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/alex/Desktop/junit5-samples/junit5-jupiter-starter-maven/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ junit5-jupiter-starter-maven ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/alex/Desktop/junit5-samples/junit5-jupiter-starter-maven/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ junit5-jupiter-starter-maven ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/alex/Desktop/junit5-samples/junit5-jupiter-starter-maven/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ junit5-jupiter-starter-maven ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.525 s
[INFO] Finished at: 2018-11-21T23:07:04+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project junit5-jupiter-starter-maven: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/alex/Desktop/junit5-samples/junit5-jupiter-starter-maven/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/alex/Desktop/junit5-samples/junit5-jupiter-starter-maven && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar /home/alex/Desktop/junit5-samples/junit5-jupiter-starter-maven/target/surefire/surefirebooter7340559277676520476.jar /home/alex/Desktop/junit5-samples/junit5-jupiter-starter-maven/target/surefire 2018-11-21T23-07-02_952-jvmRun1 surefire194873160210424536tmp surefire_03951357035306538352tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/alex/Desktop/junit5-samples/junit5-jupiter-starter-maven && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar /home/alex/Desktop/junit5-samples/junit5-jupiter-starter-maven/target/surefire/surefirebooter7340559277676520476.jar /home/alex/Desktop/junit5-samples/junit5-jupiter-starter-maven/target/surefire 2018-11-21T23-07-02_952-jvmRun1 surefire194873160210424536tmp surefire_03951357035306538352tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

```
$ mvn --version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T21:33:14+03:00)
Maven home: /home/alex/.sdkman/candidates/maven/current
Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.9.0-8-amd64", arch: "amd64", family: "unix"
```

Can someon help to fix it?

**Comment by sormuras** [comment]
```
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

Please run: `mvn -X test` and examine the output.

Travis shows the expected result: https://travis-ci.org/junit-team/junit5-samples/jobs/457943575#L1039

**Comment by sormuras** [comment]
Mhhh. Seems like your Maven installation is _broken_ or something else is preventing Surefire to start an external process...

**Comment by lx-931203** [comment]
```
$ which mvn
/home/alex/.sdkman/candidates/maven/current/bin/mvn

$ sdk update
==== BROADCAST =================================================================
* 20/11/18: Gradle 5.0-rc-4 released on SDKMAN! #gradle
* 14/11/18: Gradle 5.0-rc-3 released on SDKMAN! #gradle
* 13/11/18: Kotlin 1.3.10 released on SDKMAN! #kotlin
================================================================================
No new candidates found at this time.


ATTENTION: A new version of SDKMAN is available...

The current version is , but you have 5.7.3+337.

Would you like to upgrade now? (Y/n): y

Updating SDKMAN...
######################################################################## 100.0%
removed '/home/alex/.sdkman/bin/sdkman-init.sh'
'/home/alex/.sdkman/tmp/stage/sdkman-init.sh' -> '/home/alex/.sdkman/bin/sdkman-init.sh'
removed '/home/alex/.sdkman/src/sdkman-availability.sh'
removed '/home/alex/.sdkman/src/sdkman-broadcast.sh'
removed '/home/alex/.sdkman/src/sdkman-cache.sh'
removed '/home/alex/.sdkman/src/sdkman-current.sh'
removed '/home/alex/.sdkman/src/sdkman-default.sh'
removed '/home/alex/.sdkman/src/sdkman-env-helpers.sh'
removed '/home/alex/.sdkman/src/sdkman-flush.sh'
removed '/home/alex/.sdkman/src/sdkman-help.sh'
removed '/home/alex/.sdkman/src/sdkman-install.sh'
removed '/home/alex/.sdkman/src/sdkman-list.sh'
removed '/home/alex/.sdkman/src/sdkman-main.sh'
removed '/home/alex/.sdkman/src/sdkman-offline.sh'
removed '/home/alex/.sdkman/src/sdkman-path-helpers.sh'
removed '/home/alex/.sdkman/src/sdkman-selfupdate.sh'
removed '/home/alex/.sdkman/src/sdkman-uninstall.sh'
removed '/home/alex/.sdkman/src/sdkman-update.sh'
removed '/home/alex/.sdkman/src/sdkman-upgrade.sh'
removed '/home/alex/.sdkman/src/sdkman-use.sh'
removed '/home/alex/.sdkman/src/sdkman-utils.sh'
removed '/home/alex/.sdkman/src/sdkman-version.sh'
'/home/alex/.sdkman/tmp/stage/sdkman-availability.sh' -> '/home/alex/.sdkman/src/sdkman-availability.sh'
'/home/alex/.sdkman/tmp/stage/sdkman-broadcast.sh' -> '/home/alex/.sdkman/src/sdkman-broadcast.sh'
'/home/alex/.sdkman/tmp/stage/sdkman-cache.sh' -> '/home/alex/.sdkman/src/sdkman-cache.sh'
'/home/alex/.sdkman/tmp/stage/sdkman-current.sh' -> '/home/alex/.sdkman/src/sdkman-current.sh'
'/home/alex/.sdkman/tmp/stage/sdkman-default.sh' -> '/home/alex/.sdkman/src/sdkman-default.sh'
'/home/alex/.sdkman/tmp/stage/sdkman-env-helpers.sh' -> '/home/alex/.sdkman/src/sdkman-env-helpers.sh'
'/home/alex/.sdkman/tmp/stage/sdkman-flush.sh' -> '/home/alex/.sdkman/src/sdkman-flush.sh'
'/home/alex/.sdkman/tmp/stage/sdkman-help.sh' -> '/home/alex/.sdkman/src/sdkman-help.sh'
'/home/alex/.sdkman/tmp/stage/sdkman-install.sh' -> '/home/alex/.sdkman/src/sdkman-install.sh'
'/home/alex/.sdkman/tmp/stage/sdkman-list.sh' -> '/home/alex/.sdkman/src/sdkman-list.sh'
'/home/alex/.sdkman/tmp/stage/sdkman-main.sh' -> '/home/alex/.sdkman/src/sdkman-main.sh'
'/home/alex/.sdkman/tmp/stage/sdkman-offline.sh' -> '/home/alex/.sdkman/src/sdkman-offline.sh'
'/home/alex/.sdkman/tmp/stage/sdkman-path-helpers.sh' -> '/home/alex/.sdkman/src/sdkman-path-helpers.sh'
'/home/alex/.sdkman/tmp/stage/sdkman-selfupdate.sh' -> '/home/alex/.sdkman/src/sdkman-selfupdate.sh'
'/home/alex/.sdkman/tmp/stage/sdkman-uninstall.sh' -> '/home/alex/.sdkman/src/sdkman-uninstall.sh'
'/home/alex/.sdkman/tmp/stage/sdkman-update.sh' -> '/home/alex/.sdkman/src/sdkman-update.sh'
'/home/alex/.sdkman/tmp/stage/sdkman-upgrade.sh' -> '/home/alex/.sdkman/src/sdkman-upgrade.sh'
'/home/alex/.sdkman/tmp/stage/sdkman-use.sh' -> '/home/alex/.sdkman/src/sdkman-use.sh'
'/home/alex/.sdkman/tmp/stage/sdkman-utils.sh' -> '/home/alex/.sdkman/src/sdkman-utils.sh'
'/home/alex/.sdkman/tmp/stage/sdkman-version.sh' -> '/home/alex/.sdkman/src/sdkman-version.sh'
removed '/home/alex/.sdkman/tmp/hook_pre_vertx_3.5.4.sh'
removed '/home/alex/.sdkman/tmp/hook_pre_springboot_2.1.0.RELEASE.sh'
removed '/home/alex/.sdkman/tmp/hook_pre_scala_2.12.7.sh'
removed '/home/alex/.sdkman/tmp/hook_post_springboot_2.1.0.RELEASE.sh'
removed '/home/alex/.sdkman/tmp/hook_post_scala_2.12.7.sh'
removed '/home/alex/.sdkman/tmp/hook_post_vertx_3.5.4.sh'
removed directory '/home/alex/.sdkman/tmp/out'
removed '/home/alex/.sdkman/tmp/sdkman-5.7.3+337.zip'
removed directory '/home/alex/.sdkman/tmp'
mkdir: created directory '/home/alex/.sdkman/tmp'


Successfully upgraded SDKMAN!

Open a new terminal to start using SDKMAN 5.7.3+337.

To join our BETA channel, simply follow the instructions on:

   http://sdkman.io/install.html

Enjoy!!!


$ sdk update
No new candidates found at this time.

$ sdk install maven

Downloading: maven 3.6.0

In progress...

######################################################################## 100.0%

Installing: maven 3.6.0
Done installing!

Do you want maven 3.6.0 to be set as default? (Y/n): y

Setting maven 3.6.0 as default.

$ mvn -v
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T21:41:47+03:00)
Maven home: /home/alex/.sdkman/candidates/maven/current
Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.9.0-8-amd64", arch: "amd64", family: "unix"

$ mvn test
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< com.mycompany.app:my-app >----------------------
[INFO] Building my-app 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ my-app ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/alex/my-app/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ my-app ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ my-app ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/alex/my-app/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ my-app ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ my-app ---
[INFO] Surefire report directory: /home/alex/my-app/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Error: Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.070 s
[INFO] Finished at: 2018-11-21T23:33:33+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project my-app: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by lx-931203** [comment]
`debian` stable - the same error.

**Comment by sormuras** [comment]
Please try to upgrade the Surefire plugin to **3.0.0-M1** via...

```xml
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.0.0-M1</version>
                </plugin>
            </plugins>
        </pluginManagement>
```

**Comment by sormuras** [comment]
I guess, you were hit by https://issues.apache.org/jira/browse/SUREFIRE-1588

**Comment by lx-931203** [comment]
Latest `maven`, binary manually added to `PATH`:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.472 s
[INFO] Finished at: 2018-11-21T23:41:20+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project junit5-jupiter-starter-maven: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/alex/Desktop/junit5-samples/junit5-jupiter-starter-maven/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/alex/Desktop/junit5-samples/junit5-jupiter-starter-maven && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar /home/alex/Desktop/junit5-samples/junit5-jupiter-starter-maven/target/surefire/surefirebooter2390770726983619965.jar /home/alex/Desktop/junit5-samples/junit5-jupiter-starter-maven/target/surefire 2018-11-21T23-41-20_169-jvmRun1 surefire1323456684475287270tmp surefire_06392786965148681822tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/alex/Desktop/junit5-samples/junit5-jupiter-starter-maven && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar /home/alex/Desktop/junit5-samples/junit5-jupiter-starter-maven/target/surefire/surefirebooter2390770726983619965.jar /home/alex/Desktop/junit5-samples/junit5-jupiter-starter-maven/target/surefire 2018-11-21T23-41-20_169-jvmRun1 surefire1323456684475287270tmp surefire_06392786965148681822tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by lx-931203** [comment]
Thanks for the link.

How open that happens? Serious project, a lot of users, contributors. And so terrible fail that broke builds.

**Comment by sormuras** [comment]
> Thanks for the link.

You're welcome.

> How open that happens? Serious project, a lot of users, contributors. And so terrible fail that broke builds.

Entire (!) Maven is maintained by 5-10 people in their spare time. Time to join us and prevent such mistakes: https://twitter.com/nipafx/status/1064141177077796866
/cc @rfscholte

Did the upgrade to **Surefire 3.0.0-M1** allow both projects to be built and tested?

**Comment by lx-931203** [comment]
In fact, I am not sure in my competence - but this 5-10 developers are professionals, as I think.

And yes, next snippet
```
  <build>
    <plugins>
      <!-- JUnit 5 requires Surefire version 2.22.1 or higher -->
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.0.0-M1</version>
      </plugin>
    </plugins>
  </build>
```
fixes the build. 

Thank you for your help!
